### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by arjun024** [comment]
Thank you @mattn for the PR.

I am a little wary about the go format with the tabbed spacing and github way of package paths. I would like to keep addressing packages with relative paths.

I have cherry-picked all commits except the first 2 (expect 473603a and b436113). Thanks !!
        Arjun

**Comment by mattn** [comment]
okay. however, you will get harder to contribute or getting PRs for go
projects. because, AFAIK, 98% of gophers uses hard tabs for go. ;)

On 4/11/15, Arjun Sreedharan notifications@github.com wrote:

> Thank you @mattn for the PR.
> 
> I am a little wary about the go format with the tabbed spacing and github
> way of package paths. I would like to keep addressing packages with relative
> paths.
> 
> I have cherry-picked all commits except the first 2 (expect 473603a and
> b436113). Thanks !!
>         Arjun
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arjun024/whats/pull/1#issuecomment-91765804

## 
- Yasuhiro Matsumoto

**Comment by arjun024** [comment]
I didn't know there existed something like `go fmt`. Don't get me wrong @mattn, I do use the tab character and only tab character for indentation. But I do not prefer aligning names and types with multiple spaces. I also do not get why all lines in all go source files have to be replaced (- and +) in 473603a (go fmt).

**Comment by fwip** [comment]
`go fmt` means that you don't have to worry about styling your code - whether or not to put spaces between operators, aligning your fields, etc - and it also means that anything written in go is following the same sort of style, so everyone's familiar with it.  I have my editor (vim) set to `go fmt` every time I save.

The "go way" of packaging and imports means that I can just type `go get github.com/arjun024/whats` and have it installed straight-away and ready for use - don't even have to invoke `make`.  (It also means you wouldn't need a makefile - you can just `go build` from your directory to get the executable).

**Comment by arjun024** [comment]
This means I need to have a directory structure of `github.com/arjun024/whats` on my local machine (?); and I am expected to work on a project as if I **will** publish it at a certain location with a file structure dictated to me. Doesn't it feel very very twisted? I am surprised I don't see anyone making hue and cry over this.

**Comment by fwip** [comment]
Generally, your project would be under `$GOPATH/src/github.com/arjun024/whats/` - right along-side the other stuff installed by go.

If you really don't like it, feel free to create a symbolic link once to where you want to put it, and forget about it.

**Pull request closed without merging**
